### ISSUE TITLE
Stop Streaming flow & onDisconnect

### ISSUE THREAD

**Issue by BlueBazze** [apivideo/api.video-ios-live-stream#7]
## Summary
Noticed that the callback `onDisconnect` is not being called when executing `stopStreaming`.
Is this intentional? Or an error?

## Motivation
My users can only stream inside of a time based window. Meaning they will get disconnected when the time reaches the end time of that predefined time window. In order to accommodate this on mobile. When the end time is reached, the live stream will shut down and close the live stream page. Meaning i gotta know when the connection have been closed before i close the stream view.

## Problem
In the [stopStreaming method](https://github.com/apivideo/api.video-ios-live-stream/blob/921afc855b001607448d2eecd70a675b588048ae/Sources/ApiVideoLiveStream.swift#L197)
The `rtmpConnection.close()` might go async at some point.
Meaning the event listeners will get removed before the connection is actually closed.
Or
`rtmpConnection.close()` might not trigger the `rtmpStatusHandler` at all for some reason.

## Solution
Have a private enum that contains the status that we want the live stream to be in.
Meaning in startStreaming, we set this variable to "streaming".
So if the connection fails, we know if the user wants the stream and we can retry the connection.
In `stopStreaming`we set the enum to "stopped". When the `rtmpStatusHandler` reaches [`RTMPConnection.Code.connectClosed.rawValue`](https://github.com/apivideo/api.video-ios-live-stream/blob/921afc855b001607448d2eecd70a675b588048ae/Sources/ApiVideoLiveStream.swift#L218) we can first `onDisconnect` and afterwards check the enum, and then remove the event listeners.

Can make a pr. But want a go ahead first.

**Comment by ThibaultBee** [comment]
You are right there should be a `onDisconnect` event when user calls `stopStreaming`. I have tried to comment the part that removes the event listeners but `rtmpStatusHandler` is not called. See https://github.com/shogo4405/HaishinKit.swift/issues/671#issuecomment-623128065
Unfortunately, the easiest solution I see is to trigger `onDisconnect` in the `stopStreaming` if the application is connected.

**Comment by BlueBazze** [comment]
Took a deeper look at it.
Unfortunately you are right.

Issue fixed with [9708f21bbd0147d2cd292cbfd1880e231b6c4bf7](https://github.com/apivideo/api.video-ios-live-stream/commit/9708f21bbd0147d2cd292cbfd1880e231b6c4bf7)
